### ISSUE TITLE
The commande skepticoin-receive doesnt work

### ISSUE THREAD

**Issue by orochiwolf** [skepticoin/skepticoin#3]
When I try to excute the skepticoin-receive it throw me this error message
```
Traceback (most recent call last):
  File "./skepticoin-receive", line 8, in <module>
    sys.exit(main())
  File "/home/orochi/.local/lib/python3.8/site-packages/skepticoin/scripts/receive.py", line 18, in main
    configure_logging_from_args(args)
  File "/home/orochi/.local/lib/python3.8/site-packages/skepticoin/scripts/utils.py", line 112, in configure_logging_from_args
    if args.log_to_file:
AttributeError: 'Namespace' object has no attribute 'log_to_file'
```

I just want to know my wallet adress
After excuting the mining commande i have a file named wallet.jeson but when i read it there is a lot of pair keys i dont know witch one of them is my wallet adress.
Thank you.

**Comment by sashimi-houdini** [comment]
Fixed in `0.1.11` (see #2)

> but when i read it there is a lot of pair keys i dont know witch one of them is my wallet adress.

All of them :smile: 
more info: https://github.com/skepticoin/skepticoin/blob/master/docs/wallet.md

**Comment by orochiwolf** [comment]
> Fixed in `0.1.11` (see #2)
> 
> > but when i read it there is a lot of pair keys i dont know witch one of them is my wallet adress.
> 
> All of them 😄
> more info: https://github.com/skepticoin/skepticoin/blob/master/docs/wallet.md

Hi man,
thank you for your answers. I do now understand how the adress and wallet work.
But, I still dont understand why i have the error message ?
`Traceback (most recent call last):
  File "./skepticoin-receive", line 8, in <module>
    sys.exit(main())
  File "/home/orochi/.local/lib/python3.8/site-packages/skepticoin/scripts/receive.py", line 18, in main
    configure_logging_from_args(args)
  File "/home/orochi/.local/lib/python3.8/site-packages/skepticoin/scripts/utils.py", line 112, in configure_logging_from_args
    if args.log_to_file:
AttributeError: 'Namespace' object has no attribute 'log_to_file'`

**Comment by vanschelven** [comment]
>  But, I still dont understand why i have the error message ?

Are you on the latest version? On `0.1.10` there was a bug that produced exactly the error that you've pasted above.

**Comment by orochiwolf** [comment]
Hi,
I just want to say that it fixed. I did a 
`pip3 install --upgrade skepticoin`
And after the upgrade I  don't have the error message anymore
I know that the issue is closes but just in case someone see it
